name: Deploy Go Binaries

on:
  push:
    tags:
      - "v*"

permissions: {}

jobs:
  deploy:
    name: Build and push ${{ matrix.os }}-${{ matrix.arch }}
    
    permissions:
      contents: write

    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: ["linux", "darwin"]
        arch: ["amd64", "arm64"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Setup Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: "go.mod"

      - name: Build Go
        run: GOOS="${{ matrix.os }}" GOARCH="${{ matrix.arch }}" go build -o kleio ./cmd

      - name: Upload binaries
        uses: svenstaro/upload-release-action@6b7fa9f267e90b50a19fef07b3596790bb941741 # v2.11.3
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: kleio
          asset_name: kleio-${{ matrix.os }}-${{ matrix.arch }}
          release-id: ${{ github.ref }}
          draft: true
